### ISSUE TITLE
Error once creating a Project Task

### ISSUE THREAD

**Issue by wshamasneh** [FOSSINFOTECH/ODOO#1]
Once creating the Task and assign start and end date for the task, the following error is show up and stuck the system after it.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_order_invoicing_finished_task\models\project.py", line 55, in create
    return super(ProjectTask, self).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_timesheet\models\project.py", line 75, in create
    return super(ProjectTask, self).create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\schedule_calendar\models\schedule_calendar.py", line 129, in create
    res = super(Task, self).create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_task_code\models\project_task.py", line 22, in create
    return super(ProjectTask, self).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\pad_project\models\project.py", line 20, in create
    return super(ProjectTask, self).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hr_timesheet\models\project.py", line 60, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\bi_project_task_sequence\models\project_task.py", line 15, in create
    res = super(project_task, self).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\bi_project_issue_sequence\models\project_issue.py", line 15, in create
    res = super(project_issue, self).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project\models\project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 243, in create
    thread.message_auto_subscribe(list(create_values), values=create_values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 2159, in message_auto_subscribe
    self.message_subscribe(partner_ids=[pid], subtype_ids=subtypes, force=(subtypes != None))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 2010, in message_subscribe
    self.sudo().write({'message_follower_ids': gen})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_order_invoicing_finished_task\models\project.py", line 46, in write
    res = super(ProjectTask, self).write(vals)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\task_score_card\models\project.py", line 49, in write
    if dt.date_assign > dt.date_deadline:
TypeError: '>' not supported between instances of 'str' and 'bool'

**Comment by wshamasneh** [comment]
Closed due to another Module error, it is irrelevant.
